const mongoose = require("mongoose");
const protfolioSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
    },
    email:{
        type:String,
        required:true,
        trim:true,
        lowercase:true,
        unique:true,
    },
    mobilenum:{
        type:String,
        required:true,
        trim:true,
        unique:true,
    },
    careerobjective:{
        type:String,
        required:true,
        trim:true
    },
    skills:[{
        type:String,
        required:true,
        trim:true,
        lowercase:true
    }],
    courses:[{
        type:String,
        trim:true,
    }],
    projects:[{
        type:String,
        trim:true,
        required:true,
    }],
    sociallinks:[{
        title:{
            type:String,
            required:true,
            trim:true,
            lowercase:true
        },
        link:{
            type:String,
            required:true,
            trim:true,
        }
    }],
    extracurricularactivities:[{
        type:String,
        required:true,
        trim:true,
    }],
    additionaldetails:[{
        type:String,
        required:true,
        trim:true,
    }],
    address:{
        city:{
            type:String,
            required:true,
            trim:true,
        },
        state:{
            type:String,
            required:true,
            trim:true
        }
    },
    education:[{
        degree:{
            type:String,
            required:true,
            trim:true,
        },
        institution:{
            type:String,
            required:true,
            trim:true
        },
        year:{
            type:String,
            required:true,
            trim:true
        },
    }],
    experience:[{
        company:{
            type:String,
            trim:true
        },
        role:{
            type:String,
            trim:true
        },
        duration:{
            type:String,
            trim:true
        },
    }],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    }
} , {timestamps:true});

const Portfolio = mongoose.model("Portfolio" , protfolioSchema);
module.exports = Portfolio;