const mongoose = require("mongoose");
const protfolioSchema = new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
    },
    email:{
        type:String,
        required:true,
        trim:true,
        lowercase:true,
        unique:true,
    },
    mobilenumber:{
        type:String,
        required:true,
        trim:true,
        unique:true,
    },
    careerobjective:{
        type:String,
        required:true,
        trim:true
    },
    skills:[{
        type:String,
        trim:true,
        lowercase:true,
        required:true
    }],
    courses:[{
        type:String,
        trim:true,
    }],
    projects:{
        type:[
            {
                title:{
                    type:String,
                    trim:true,
                    required:true,
                },
                link:{
                    type:String,
                    trim:true,
                    required:true
                },
            }
        ],
        required:true,
    },
    sociallinks:{
        type:[
            {
                socialmedia:{
                    type:String,
                    required:true,
                    trim:true,
                    lowercase:true
                },
                link:{
                    type:String,
                    required:true,
                    trim:true,
                },
            }
        ],
        required:true,
    },
    extracurricularactivities:[{
        type:String,
        trim:true,
    }],
    address:{
        city:{
            type:String,
            required:true,
            trim:true,
        },
        state:{
            type:String,
            required:true,
            trim:true
        },
        country:{
            type:String,
            required:true,
            trim:true
        },
    },
    education:[{
        degree:{
            type:String,
            required:true,
            trim:true,
        },
        institution:{
            type:String,
            required:true,
            trim:true
        },
        year:{
            type:String,
            required:true,
            trim:true
        },
    }],
    experience:[{
        company:{
            type:String,
            trim:true,
            required:true,
        },
        role:{
            type:String,
            trim:true,
            required:true,
        },
        years:{
            type:String,
            trim:true,
            required:true,
        },
    }],
    resume:{
        type:String,
        required:true,
        trim:true
    },
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    }
} , {timestamps:true});

const Portfolio = mongoose.model("Portfolio" , protfolioSchema);
module.exports = Portfolio;